# See http://www.appveyor.com/docs/appveyor-yml

version: '{build}'

branches:
  except:
  - /^travis.*$/

init:
- git config --global core.autocrlf input

shallow_clone: true

os: Visual Studio 2015

environment:
  matrix:
  - CMAKE_GENERATOR: "Visual Studio 14 2015"
    CMAKE_PREFIX_PATH: C:\Qt\5.5\msvc2013
  - CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
    CMAKE_PREFIX_PATH: C:\Qt\5.5\msvc2013_64

matrix:
  fast_finish: true

configuration: Debug

before_build:
- cmake -H. -Bbuild -G "%CMAKE_GENERATOR%" "-DCMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH%" -DENABLE_GUI=ON

build:
  project: build\apitrace.sln
  verbosity: minimal

after_build:
- cmake --build build --use-stderr --config "%CONFIGURATION%" --target package -- /verbosity:minimal

#artifacts:
#- path: build/apitrace-*.7z
#  name: apitrace
